<!DOCTYPE html>
<html>
    <head>
        <title>PassHash - Generate a password hash using PHP's native password API</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='//fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen">
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    </head>
    <body>
        <header>
            <div class="content">
                <h1><a href="/">PassHash</a></h1>
                <h2>Generate a password hash using PHP's native password API</h2>
            </div>
        </header>
        <?php echo $content; ?>
        <footer>
            <ul>
                <li>PassHash - Generate a password hash using PHP's native password API</li>
                <li>|</li>
                <li><a href="https://github.com/PeeHaa/PassHash" target="_blank">Projectpage on GitHub</a></li>
                <li>|</li>
                <li>License: <a href="http://spdx.org/licenses/MIT" target="_blank">MIT</a></li>
                <li>|</li>
                <li>Developed and maintained by: <a href="https://pieterhordijk.com" target="_blank">Pieter Hordijk</a></li>
            </ul>
        </footer>
        <script src="/js/main.js"></script>
    </body>
</html>
